import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type ThemedColor, tokens } from '../src/index.js';

const KEBAB_RE = /[A-Z]/g;

function kebab(name: string): string {
	return name.replace(KEBAB_RE, (letter) => `-${letter.toLowerCase()}`);
}

function colorRoles(): [string, ThemedColor][] {
	const { category, ...roles } = tokens.color;
	const flat: [string, ThemedColor][] = Object.entries(roles).map(([role, value]) => [
		kebab(role),
		value,
	]);
	for (const [slug, value] of Object.entries(category)) {
		flat.push([slug, value]);
	}
	return flat;
}

function block(selector: string, declarations: string[], indent = ''): string {
	const body = declarations.map((line) => `${indent}\t${line}`).join('\n');
	return `${indent}${selector} {\n${body}\n${indent}}`;
}

/**
 * Emits dist/theme.css: raw --eq-* custom properties flipped by
 * [data-theme] (with a prefers-color-scheme fallback for no-JS visitors),
 * then Tailwind v4 @theme bindings so utilities like bg-surface or
 * text-physics resolve through the theme-aware variables.
 */
function buildThemeCss(): string {
	const roles = colorRoles();
	const light = roles.map(([name, value]) => `--eq-${name}: ${value.light};`);
	const dark = roles.map(([name, value]) => `--eq-${name}: ${value.dark};`);

	const themeInline = [
		...roles.map(([name]) => `--color-${name}: var(--eq-${name});`),
		`--font-sans: ${tokens.font.sans};`,
		`--font-mono: ${tokens.font.mono};`,
	];

	const themeStatic = [
		`--spacing: ${tokens.spacingBase};`,
		...Object.entries(tokens.radius).map(([name, value]) => `--radius-${name}: ${value};`),
		...Object.entries(tokens.text).flatMap(([name, ramp]) => [
			`--text-${name}: ${ramp.size};`,
			`--text-${name}--line-height: ${ramp.lineHeight};`,
		]),
	];

	return [
		'/* Generated by @equreka/tokens scripts/build-theme.ts — do not edit. */',
		block(':root', light),
		block(":root[data-theme='dark']", dark),
		`@media (prefers-color-scheme: dark) {\n${block(":root:not([data-theme='light'])", dark, '\t')}\n}`,
		block('@theme inline', themeInline),
		block('@theme', themeStatic),
		'',
	].join('\n\n');
}

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'theme.css'), buildThemeCss());
console.log(`@equreka/tokens: wrote ${join(outDir, 'theme.css')}`);
